name: Run Stock Bot
on:
  schedule:
    - cron: '50 1 * * 1-5' # 這是世界時間，等於台灣時間週一至週五 09:50
  workflow_dispatch: # 讓你可以點按鈕測試
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install
        run: pip install -r requirements.txt
      - name: Run
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
        run: python bot.py

