name: Run Stock Bot

on:
  schedule:
    # 23:49 UTC = 台灣 07:49 (前一天跨當天)
    # 06:49 UTC = 台灣 9:49
    - cron: '49 23,1 * * 1-5'

  push:
    branches: [ main ] # 你每次存檔也會自動跑，方便測試
  workflow_dispatch: # 保留手動按鈕

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Install dependencies
        run: |
          pip install yfinance twilio pandas matplotlib requests

      - name: Run Bot
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          MY_PHONE: ${{ secrets.MY_PHONE }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: python bot.py
